package com.muslima.myrac.amimal

const val name1="Tiger"
const val bio1="The coat of tigers is a reddish-orange coat and there are vertical black stripes on the shoulders and flanks that vary in size, spacing, and length. Some subspecies have fur that is paler, some being almost completely white with either dark brown or black stripes along their flanks and shoulders. The muzzle, throat, chest, belly, and underside of the limbs are white or light. Above the eyes, of these beautiful animals, there is a white color that extends to the cheeks. On the back of their ears, there is a white spot. Their tail is reddish-orange in color and ringed by several dark bands."
const val img1="https://s3.animalia.bio/animals/photos/full/1.25x1/in-ranthambhore-rajasthan-indiajpg.webp?id=24523db916f6a72633f3db5935e36db1"
const val name2="Killer Whale"
const val bio2="Killer whales have long, round bodies with big dorsal fins in the middle of their back. Their bodies are black with white patches underneath and near their eyes. These distinctive patterns help to camouflage them when they are searching for food. In newborns, the white parts of their bodies have an orange tinge"
const val img2="https://s3.animalia.bio/animals/photos/small/1x1/glacier-bay.webp?id=1939597045f676f5e3f1018265a251da"
const val name3="Grey Wolf"
const val bio3="The Grey wolf is the largest extant member of the family Canidae. It is also distinguished from other Canis species by its less pointed ears and muzzle, as well as a shorter torso and a longer tail. The wolf is nonetheless related closely enough to smaller Canis species, such as the coyote and the golden jackal, to produce fertile hybrids with them. Females are smaller than males. Male wolves have straight tails and narrow chests. The feet of males are large and the legs are long. The overall color of the Grey wolf's fur is typically grey with black markings and lighter underparts, though wolves can occasionally be black, brown, red, or even pure white. Grey wolves have very thick fur, consisting of a coarse outer coat, which covers the soft undercoat. Due to the acute sense of hearing and keen sense of smell, the animal can successfully track down prey. In addition, the long legs allow them to make long steps, promoting high speed during the chase."
const val img3="https://s3.animalia.bio/animals/photos/small/1x1/8hMRXCC1VkBzfHxd45Vk.webp?id=0c6e65b03a518c13207caae286ebda6e"